// Mock projects shaped to match the backend Project model (with ownerId populated).
export const mockProjects = [
  {
    id: "p1",
    title: "Neural Synapse Mapping in VR",
    description: "Real-time volumetric visualization of synaptic pathways for neuroscience labs.",
    category: "Research",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1200&q=80",
    techstack: ["Unity", "VR", "Python"],
    rolesNeeded: ["Researcher"],
    commitment: "side_project",
    status: "recruiting",
    ownerId: {
      _id: "u1",
      name: "Dr. Julian Vance",
      email: "julian.vance@example.com",
      avatar: "https://i.pravatar.cc/100?img=11",
    },
    members: [],
    engagement: { likes: 432, views: 1200 },
    createdAt: "2024-08-01T10:00:00.000Z",
    updatedAt: "2024-09-01T10:00:00.000Z",
  },
  {
    id: "p2",
    title: "Autonomous Lunar Swarmers",
    description: "Decentralized control algorithms for micro-rovers in extreme regolith conditions.",
    category: "Engineering",
    imageUrl: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80",
    techstack: ["ROS", "C++", "ML"],
    rolesNeeded: ["ML Engineer"],
    commitment: "startup",
    status: "in_progress",
    ownerId: {
      _id: "u2",
      name: "Elena Thorne",
      email: "elena.thorne@example.com",
      avatar: "https://i.pravatar.cc/100?img=31",
    },
    members: [],
    engagement: { likes: 156, views: 890 },
    createdAt: "2024-07-20T08:30:00.000Z",
    updatedAt: "2024-08-15T08:30:00.000Z",
  },
  {
    id: "p3",
    title: "Ethical AI Frameworks 2.0",
    description: "Applying symbolic constraints and policy checks to modern language models.",
    category: "Computing",
    imageUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=80",
    techstack: ["Node.js", "LLM", "Python"],
    rolesNeeded: ["Backend"],
    commitment: "side_project",
    status: "recruiting",
    ownerId: {
      _id: "u3",
      name: "Markus Chen",
      email: "markus.chen@example.com",
      avatar: "https://i.pravatar.cc/100?img=20",
    },
    members: [],
    engagement: { likes: 1100, views: 2400 },
    createdAt: "2024-06-30T11:30:00.000Z",
    updatedAt: "2024-07-21T11:30:00.000Z",
  },
  {
    id: "p4",
    title: "CRISPR for Coral Restoration",
    description: "Engineering heat-resistant coral strains to protect reef ecosystems.",
    category: "Biology",
    imageUrl: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1200&q=80",
    techstack: ["Bioinformatics"],
    rolesNeeded: ["Biologist"],
    commitment: "startup",
    status: "in_progress",
    ownerId: {
      _id: "u4",
      name: "Sarah Jenkins",
      email: "sarah.jenkins@example.com",
      avatar: "https://i.pravatar.cc/100?img=47",
    },
    members: [],
    engagement: { likes: 920, views: 3100 },
    createdAt: "2024-05-20T09:15:00.000Z",
    updatedAt: "2024-06-10T09:15:00.000Z",
  },
  {
    id: "p5",
    title: "Plasma Propulsion Metrics",
    description: "Benchmarking thrust efficiency for compact plasma propulsion prototypes.",
    category: "Space",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    techstack: ["MATLAB", "CFD"],
    rolesNeeded: ["Data Analyst"],
    commitment: "hackathon",
    status: "recruiting",
    ownerId: {
      _id: "u5",
      name: "David Orion",
      email: "david.orion@example.com",
      avatar: "https://i.pravatar.cc/100?img=14",
    },
    members: [],
    engagement: { likes: 88, views: 760 },
    createdAt: "2024-04-20T13:40:00.000Z",
    updatedAt: "2024-05-11T13:40:00.000Z",
  },
  {
    id: "p6",
    title: "Distributed Ledger Consensus",
    description: "New protocol variants to reduce proof-of-stake energy overhead.",
    category: "Software",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    techstack: ["Rust", "Go"],
    rolesNeeded: ["Frontend"],
    commitment: "side_project",
    status: "recruiting",
    ownerId: {
      _id: "u6",
      name: "Aria Sol",
      email: "aria.sol@example.com",
      avatar: "https://i.pravatar.cc/100?img=24",
    },
    members: [],
    engagement: { likes: 610, views: 1500 },
    createdAt: "2024-03-15T12:20:00.000Z",
    updatedAt: "2024-04-03T12:20:00.000Z",
  },
  {
    id: "p7",
    title: "Graphite-Anode Efficiency",
    description: "Improving battery cycle life using nanostructured graphite surfaces.",
    category: "Chemistry",
    imageUrl: "https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?auto=format&fit=crop&w=1200&q=80",
    techstack: ["Materials", "Python"],
    rolesNeeded: ["Researcher"],
    commitment: "hackathon",
    status: "completed",
    ownerId: {
      _id: "u7",
      name: "Dr. Robert Hales",
      email: "robert.hales@example.com",
      avatar: "https://i.pravatar.cc/100?img=8",
    },
    members: [],
    engagement: { likes: 112, views: 540 },
    createdAt: "2024-02-10T10:10:00.000Z",
    updatedAt: "2024-03-01T10:10:00.000Z",
  },
  {
    id: "p8",
    title: "Hydro-Kinetic Coastal Mesh",
    description: "Capturing tidal energy with low-impact flexible polymer grids.",
    category: "Environment",
    imageUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1200&q=80",
    techstack: ["CAD", "Simulation"],
    rolesNeeded: ["Mechanical"],
    commitment: "side_project",
    status: "archived",
    ownerId: {
      _id: "u8",
      name: "Lila Meadows",
      email: "lila.meadows@example.com",
      avatar: "https://i.pravatar.cc/100?img=49",
    },
    members: [],
    engagement: { likes: 445, views: 2100 },
    createdAt: "2024-01-25T16:00:00.000Z",
    updatedAt: "2024-02-20T16:00:00.000Z",
  },
];

export const projectRoles = ["all", "Researcher", "ML Engineer", "Backend", "Frontend", "Biologist", "Data Analyst", "Mechanical"];
export const projectCommitments = ["all", "hackathon", "side_project", "startup"];
export const projectSortOptions = ["recent", "popular"];
